### ISSUE TITLE
Wrong namespace attribution

### ISSUE THREAD

**Issue by papadop** [m7thon/doxy2swig#6]
It seems that in the presence of an innernamespace doxy2swig attributes compundefs to the wrong namespace.
Here is a simplified xml input:

<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.9.1" xml:lang="en-US">
  <compounddef id="namespaceOpenMEEG" kind="namespace" language="C++">
    <compoundname>OpenMEEG</compoundname>
    <innerclass refid="classOpenMEEG_1_1analyticS" prot="public">OpenMEEG::analyticS</innerclass>
    [...]
    <innernamespace refid="namespaceOpenMEEG_1_1maths">OpenMEEG::maths</innernamespace>
      <sectiondef kind="enum">
      <memberdef kind="enum" id="namespaceOpenMEEG_1a116cd75013bceb99a50b15a0b4cc4c39" prot="public" static="no" strong="no">
        <type></type>
        <name>DeepCopy</name>
        <enumvalue id="namespaceOpenMEEG_1a116cd75013bceb99a50b15a0b4cc4c39a0a5074927f0550ab6844f73d86418115" prot="public">
          <name>DEEP_COPY</name>
        </enumvalue>
      </memberdef>
      </sectiondef>
</sectiondef>
  </compounddef>
</doxygen>

For me, the innerspace entry just says that there exists a sub-namepsace named OpenMEEG::maths, not that the defs in the file are in that namespace as doxy2swig currently does. And indeed, in the code from which this example was generated, DEEPCOPY (and all the def that are mentioned in the various sectiondef sections) is defined at the OpenMEEG namespace level not in OpenMEEG::maths which are described in another namespace file.

**Comment by papadop** [comment]
Without being sure, here is a patch that corrects this
[PATCH.txt](https://github.com/m7thon/doxy2swig/files/8198171/PATCH.txt)

**Comment by m7thon** [comment]
Hi, thanks. I have not really been maintaining this code. There is an open PR for the same issue you report. Could you please check if that fixes the issue? I'd just commit the open PR (it seems to me this does something very similar to your patch).

Also, is this (`doxy2swig`) still relevant at all? I believe newer swig versions (as of 4.0?) should support parsing of doxygen strings directly.

**Comment by papadop** [comment]
Yes the code in the PR fixes the problem.

For the relevance of doxy2swig, I actually do not know. swig does so many things, it is difficult to know all the features.... I'm just maintaining this part of the code, which was written long time ago. I never questioned the relevance of the approach. If I can simplify the setup and use the swig docstring generation, this is good. I will see if this is easy to do. Thank's for mentioning it.

**Comment by papadop** [comment]
And I confirm that %feature("autodoc", "1") seems to do the job directly in swig. So I do not use doxy2swig any longer. Thank's for the advice.

**Comment by m7thon** [comment]
I merged the (long outstanding) PR and added a comment to the README pointing to the direct support in swig.
